// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpellGenerator.Data;

#nullable disable

namespace SpellGenerator.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240916155717_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.33");

            modelBuilder.Entity("SpellGenerator.Data.DataModels.AddOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InstabilityValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifierValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpellId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.ToTable("AddOns");
                });

            modelBuilder.Entity("SpellGenerator.Data.DataModels.Magic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpellId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.ToTable("Magics");
                });

            modelBuilder.Entity("SpellGenerator.Data.DataModels.Mastery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentMasteryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpellId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentMasteryId");

                    b.HasIndex("SpellId");

                    b.ToTable("Masteries");
                });

            modelBuilder.Entity("SpellGenerator.Data.DataModels.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ManaCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpellBookId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpellBookId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("SpellGenerator.Data.DataModels.SpellBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SpellBooks");
                });

            modelBuilder.Entity("SpellGenerator.Data.DataModels.AddOn", b =>
                {
                    b.HasOne("SpellGenerator.Data.DataModels.Spell", null)
                        .WithMany("AddOns")
                        .HasForeignKey("SpellId");
                });

            modelBuilder.Entity("SpellGenerator.Data.DataModels.Magic", b =>
                {
                    b.HasOne("SpellGenerator.Data.DataModels.Spell", null)
                        .WithMany("RequieredMagics")
                        .HasForeignKey("SpellId");
                });

            modelBuilder.Entity("SpellGenerator.Data.DataModels.Mastery", b =>
                {
                    b.HasOne("SpellGenerator.Data.DataModels.Mastery", "ParentMastery")
                        .WithMany()
                        .HasForeignKey("ParentMasteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellGenerator.Data.DataModels.Spell", null)
                        .WithMany("RequieredMasteries")
                        .HasForeignKey("SpellId");

                    b.Navigation("ParentMastery");
                });

            modelBuilder.Entity("SpellGenerator.Data.DataModels.Spell", b =>
                {
                    b.HasOne("SpellGenerator.Data.DataModels.SpellBook", null)
                        .WithMany("StoredSpells")
                        .HasForeignKey("SpellBookId");
                });

            modelBuilder.Entity("SpellGenerator.Data.DataModels.Spell", b =>
                {
                    b.Navigation("AddOns");

                    b.Navigation("RequieredMagics");

                    b.Navigation("RequieredMasteries");
                });

            modelBuilder.Entity("SpellGenerator.Data.DataModels.SpellBook", b =>
                {
                    b.Navigation("StoredSpells");
                });
#pragma warning restore 612, 618
        }
    }
}
